### ISSUE TITLE
Can't make bookmarklet

### ISSUE THREAD

**Issue by Mennaruuk** [jstrieb/procrastinate#1]
Using Firefox. I'm copying all the code on [this page](https://raw.githubusercontent.com/jstrieb/procrastinate/main/bookmarklet.js) and dragging it into the Bookmarks Toolbar, yet I'm shown a little black circle with a diagonal line in the middle. I tried copying all the code and pasting it in the URL part of an existing bookmark, but when I clicked it, it didn't work.

**Comment by jstrieb** [comment]
Thanks for pointing this out! I'm having the same problem, and an update is in the works.
